# Generated by Django 6.0.1 on 2026-01-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='assigned_to',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='3', max_length=255),
            preserve_default=False,
        ),
    ]
